apiVersion: v1
kind: Pod
metadata: 
  name: testing
  namespace: coder
  labels:
    name: testing
spec:
  containers:
  - name: container-testing
    image: bitbull/webserver
    ports: 
    - containerPort: 80
    
    env:
    - name: FIRST_CONFIG
      valueFrom: 
        configMapKeyRef:
          name: test-config
          key: Description 





